apiVersion: batch/v1
kind: Job
metadata:
  name: analytics-db-migrate
  annotations:
    tilt.dev/restartOnChange: "true"
spec:
  backoffLimit: 1
  template:
    spec:
      restartPolicy: Never
      containers:
        - name: migrate
          image: routepulse/analytics-migrate
          args:
           - "-dir=/migrations"
           - "clickhouse"
           - "tcp://$(CLICKHOUSE_USER):$(CLICKHOUSE_PASSWORD)@clickhouse:9000/$(CLICKHOUSE_DB)"
           - "up"
          env:
            - name: CLICKHOUSE_USER
              valueFrom:
                secretKeyRef:
                  name: routepulse-credentials
                  key: user
            - name: CLICKHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: routepulse-credentials
                  key: password
            - name: CLICKHOUSE_DB
              valueFrom:
                secretKeyRef:
                  name: routepulse-credentials
                  key: db-ch
