apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: clickhouse
spec:
  serviceName: clickhouse
  replicas: 1
  selector:
    matchLabels:
      app: clickhouse
  template:
    metadata:
      labels:
        app: clickhouse
    spec:
      terminationGracePeriodSeconds: 30
      containers:
        - name: clickhouse
          image: clickhouse/clickhouse-server:24.8
          ports:
          - containerPort: 8123
          - containerPort: 9000
          env:
            - name: CLICKHOUSE_DB
              valueFrom:
                secretKeyRef:
                  name: routepulse-credentials
                  key: db-ch
            - name: CLICKHOUSE_USER
              valueFrom:
                secretKeyRef:
                  name: routepulse-credentials
                  key: user
            - name: CLICKHOUSE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: routepulse-credentials
                  key: password
            - name: CLICKHOUSE_DEFAULT_ACCESS_MANAGEMENT
              value: "1"
          volumeMounts:
            - name: ch-vol
              mountPath: /var/lib/clickhouse/
          livenessProbe:
            httpGet:
              path: /ping
              port: 8123
            initialDelaySeconds: 60
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 1
          readinessProbe:
            httpGet:
              path: /ping
              port: 8123
            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 3
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1"
  volumeClaimTemplates:
    - metadata:
        name: ch-vol
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi
---
# Service Config
apiVersion: v1
kind: Service
metadata:
  name: clickhouse
spec:
  type: ClusterIP
  selector:
    app: clickhouse
  ports:
    - name: http
      port: 8123
      targetPort: 8123
    - name: native
      port: 9000
      targetPort: 9000