apiVersion: apps/v1
kind: Deployment
metadata:
  name: identity-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: identity-service
  template:
    metadata:
      labels:
        app: identity-service
    spec:
      containers:
        - name: identity-service
          image: routepulse/identity-service
          ports:
            - containerPort: 9090
          resources:
            requests:
              memory: "128Mi"
              cpu: "125m"
            limits:
              memory: "128Mi"
              cpu: "125m"
          env:
          - name: BREVO_SMTP_KEY
            valueFrom:
              secretKeyRef:
                name: routepulse-credentials
                key: brevo-smtp-key
          - name: BREVO_SMTP_FROM
            valueFrom:
              secretKeyRef:
                name: routepulse-credentials
                key: brevo-from
          - name: BREVO_SMTP_HOST
            valueFrom:
              configMapKeyRef:
                name: identity-config
                key: BREVO_SMTP_HOST
          - name: BREVO_SMTP_PORT
            valueFrom:
              configMapKeyRef:
                name: identity-config
                key: BREVO_SMTP_PORT
          - name: IDENTITY_SERVICE_ADDR
            valueFrom:
              configMapKeyRef:
                name: identity-config
                key: IDENTITY_SERVICE_ADDR
          - name: IDENTITY_SERVICE_PORT
            valueFrom:
              configMapKeyRef:
                name: identity-config
                key: IDENTITY_SERVICE_PORT
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: routepulse-credentials
                key: user
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: routepulse-credentials
                key: password
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: routepulse-credentials
                key: db
---
apiVersion: v1
kind: Service
metadata:
  name: identity-service
spec:
  type: LoadBalancer
  ports:
    - port: 9090
      targetPort: 9090
  selector:
    app: identity-service
