apiVersion: apps/v1
kind: Deployment
metadata:
  name: web
  labels:
    app: web
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web
          image: routepulse/frontend/web
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5173
              name: http
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "2Gi"
              cpu: "1"
          env:
            # put this in configMap or secrets
            - name: NODE_ENV
              value: "development"
          # - name: NEXT_PUBLIC_API_URL
          #   value: "http://api-gateway:8081"
          # - name: NEXT_PUBLIC_WEBSOCKET_URL
          #   value: "ws://api-gateway:8081/ws"
          readinessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 2
            periodSeconds: 2
            timeoutSeconds: 2
          livenessProbe:
            httpGet:
              path: /
              port: http
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 10
            failureThreshold: 3
---
# Service Config
apiVersion: v1
kind: Service
metadata:
  name: web
spec:
  type: LoadBalancer
  selector:
    app: web
  ports:
    - port: 5173
      targetPort: 5173
