// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: analytics.proto

package analytics

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VehiclesInTransitResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         uint64                 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VehiclesInTransitResponse) Reset() {
	*x = VehiclesInTransitResponse{}
	mi := &file_analytics_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehiclesInTransitResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehiclesInTransitResponse) ProtoMessage() {}

func (x *VehiclesInTransitResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehiclesInTransitResponse.ProtoReflect.Descriptor instead.
func (*VehiclesInTransitResponse) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{0}
}

func (x *VehiclesInTransitResponse) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

type TripsTodayResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Count         uint64                 `protobuf:"varint,1,opt,name=count,proto3" json:"count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TripsTodayResponse) Reset() {
	*x = TripsTodayResponse{}
	mi := &file_analytics_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TripsTodayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TripsTodayResponse) ProtoMessage() {}

func (x *TripsTodayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_analytics_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TripsTodayResponse.ProtoReflect.Descriptor instead.
func (*TripsTodayResponse) Descriptor() ([]byte, []int) {
	return file_analytics_proto_rawDescGZIP(), []int{1}
}

func (x *TripsTodayResponse) GetCount() uint64 {
	if x != nil {
		return x.Count
	}
	return 0
}

var File_analytics_proto protoreflect.FileDescriptor

const file_analytics_proto_rawDesc = "" +
	"\n" +
	"\x0fanalytics.proto\x12\tanalytics\x1a\x1bgoogle/protobuf/empty.proto\"1\n" +
	"\x19VehiclesInTransitResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x04R\x05count\"*\n" +
	"\x12TripsTodayResponse\x12\x14\n" +
	"\x05count\x18\x01 \x01(\x04R\x05count2\xb0\x01\n" +
	"\x10AnalyticsService\x12T\n" +
	"\x14GetVehiclesInTransit\x12\x16.google.protobuf.Empty\x1a$.analytics.VehiclesInTransitResponse\x12F\n" +
	"\rGetTripsToday\x12\x16.google.protobuf.Empty\x1a\x1d.analytics.TripsTodayResponseB\"Z shared/proto/analytics;analyticsb\x06proto3"

var (
	file_analytics_proto_rawDescOnce sync.Once
	file_analytics_proto_rawDescData []byte
)

func file_analytics_proto_rawDescGZIP() []byte {
	file_analytics_proto_rawDescOnce.Do(func() {
		file_analytics_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_analytics_proto_rawDesc), len(file_analytics_proto_rawDesc)))
	})
	return file_analytics_proto_rawDescData
}

var file_analytics_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_analytics_proto_goTypes = []any{
	(*VehiclesInTransitResponse)(nil), // 0: analytics.VehiclesInTransitResponse
	(*TripsTodayResponse)(nil),        // 1: analytics.TripsTodayResponse
	(*emptypb.Empty)(nil),             // 2: google.protobuf.Empty
}
var file_analytics_proto_depIdxs = []int32{
	2, // 0: analytics.AnalyticsService.GetVehiclesInTransit:input_type -> google.protobuf.Empty
	2, // 1: analytics.AnalyticsService.GetTripsToday:input_type -> google.protobuf.Empty
	0, // 2: analytics.AnalyticsService.GetVehiclesInTransit:output_type -> analytics.VehiclesInTransitResponse
	1, // 3: analytics.AnalyticsService.GetTripsToday:output_type -> analytics.TripsTodayResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_analytics_proto_init() }
func file_analytics_proto_init() {
	if File_analytics_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_analytics_proto_rawDesc), len(file_analytics_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_analytics_proto_goTypes,
		DependencyIndexes: file_analytics_proto_depIdxs,
		MessageInfos:      file_analytics_proto_msgTypes,
	}.Build()
	File_analytics_proto = out.File
	file_analytics_proto_goTypes = nil
	file_analytics_proto_depIdxs = nil
}
