// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: fleet.proto

package fleet

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Vehicle struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	VehicleId      string                 `protobuf:"bytes,1,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	PlateNumber    string                 `protobuf:"bytes,3,opt,name=plate_number,json=plateNumber,proto3" json:"plate_number,omitempty"`
	VehicleType    string                 `protobuf:"bytes,4,opt,name=vehicle_type,json=vehicleType,proto3" json:"vehicle_type,omitempty"`
	Capacity       int32                  `protobuf:"varint,5,opt,name=capacity,proto3" json:"capacity,omitempty"`
	Status         string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt      int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Vehicle) Reset() {
	*x = Vehicle{}
	mi := &file_fleet_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Vehicle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Vehicle) ProtoMessage() {}

func (x *Vehicle) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Vehicle.ProtoReflect.Descriptor instead.
func (*Vehicle) Descriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{0}
}

func (x *Vehicle) GetVehicleId() string {
	if x != nil {
		return x.VehicleId
	}
	return ""
}

func (x *Vehicle) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *Vehicle) GetPlateNumber() string {
	if x != nil {
		return x.PlateNumber
	}
	return ""
}

func (x *Vehicle) GetVehicleType() string {
	if x != nil {
		return x.VehicleType
	}
	return ""
}

func (x *Vehicle) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

func (x *Vehicle) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Vehicle) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type Driver struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DriverId       string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	FirstName      string                 `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName       string                 `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	VehicleId      string                 `protobuf:"bytes,5,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	Status         string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt      int64                  `protobuf:"varint,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Driver) Reset() {
	*x = Driver{}
	mi := &file_fleet_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Driver) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Driver) ProtoMessage() {}

func (x *Driver) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Driver.ProtoReflect.Descriptor instead.
func (*Driver) Descriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{1}
}

func (x *Driver) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *Driver) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *Driver) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *Driver) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *Driver) GetVehicleId() string {
	if x != nil {
		return x.VehicleId
	}
	return ""
}

func (x *Driver) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Driver) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type Trip struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TripId         string                 `protobuf:"bytes,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	OrganizationId string                 `protobuf:"bytes,2,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	VehicleId      string                 `protobuf:"bytes,3,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	DriverId       string                 `protobuf:"bytes,4,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Status         string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	StartTime      int64                  `protobuf:"varint,6,opt,name=start_time,json=startTime,proto3" json:"start_time,omitempty"`
	EndTime        int64                  `protobuf:"varint,7,opt,name=end_time,json=endTime,proto3" json:"end_time,omitempty"`
	CreatedAt      int64                  `protobuf:"varint,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *Trip) Reset() {
	*x = Trip{}
	mi := &file_fleet_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Trip) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Trip) ProtoMessage() {}

func (x *Trip) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Trip.ProtoReflect.Descriptor instead.
func (*Trip) Descriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{2}
}

func (x *Trip) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

func (x *Trip) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *Trip) GetVehicleId() string {
	if x != nil {
		return x.VehicleId
	}
	return ""
}

func (x *Trip) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *Trip) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Trip) GetStartTime() int64 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *Trip) GetEndTime() int64 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *Trip) GetCreatedAt() int64 {
	if x != nil {
		return x.CreatedAt
	}
	return 0
}

type CreateVehicleRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	PlateNumber    string                 `protobuf:"bytes,2,opt,name=plate_number,json=plateNumber,proto3" json:"plate_number,omitempty"`
	VehicleType    string                 `protobuf:"bytes,3,opt,name=vehicle_type,json=vehicleType,proto3" json:"vehicle_type,omitempty"`
	Capacity       int32                  `protobuf:"varint,4,opt,name=capacity,proto3" json:"capacity,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateVehicleRequest) Reset() {
	*x = CreateVehicleRequest{}
	mi := &file_fleet_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVehicleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVehicleRequest) ProtoMessage() {}

func (x *CreateVehicleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVehicleRequest.ProtoReflect.Descriptor instead.
func (*CreateVehicleRequest) Descriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{3}
}

func (x *CreateVehicleRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *CreateVehicleRequest) GetPlateNumber() string {
	if x != nil {
		return x.PlateNumber
	}
	return ""
}

func (x *CreateVehicleRequest) GetVehicleType() string {
	if x != nil {
		return x.VehicleType
	}
	return ""
}

func (x *CreateVehicleRequest) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

type CreateVehicleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vehicle       *Vehicle               `protobuf:"bytes,1,opt,name=vehicle,proto3" json:"vehicle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateVehicleResponse) Reset() {
	*x = CreateVehicleResponse{}
	mi := &file_fleet_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateVehicleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateVehicleResponse) ProtoMessage() {}

func (x *CreateVehicleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateVehicleResponse.ProtoReflect.Descriptor instead.
func (*CreateVehicleResponse) Descriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{4}
}

func (x *CreateVehicleResponse) GetVehicle() *Vehicle {
	if x != nil {
		return x.Vehicle
	}
	return nil
}

type GetVehicleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VehicleId     string                 `protobuf:"bytes,1,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVehicleRequest) Reset() {
	*x = GetVehicleRequest{}
	mi := &file_fleet_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVehicleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVehicleRequest) ProtoMessage() {}

func (x *GetVehicleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVehicleRequest.ProtoReflect.Descriptor instead.
func (*GetVehicleRequest) Descriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{5}
}

func (x *GetVehicleRequest) GetVehicleId() string {
	if x != nil {
		return x.VehicleId
	}
	return ""
}

type GetVehicleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vehicle       *Vehicle               `protobuf:"bytes,1,opt,name=vehicle,proto3" json:"vehicle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetVehicleResponse) Reset() {
	*x = GetVehicleResponse{}
	mi := &file_fleet_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetVehicleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetVehicleResponse) ProtoMessage() {}

func (x *GetVehicleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetVehicleResponse.ProtoReflect.Descriptor instead.
func (*GetVehicleResponse) Descriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{6}
}

func (x *GetVehicleResponse) GetVehicle() *Vehicle {
	if x != nil {
		return x.Vehicle
	}
	return nil
}

type ListVehiclesRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListVehiclesRequest) Reset() {
	*x = ListVehiclesRequest{}
	mi := &file_fleet_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVehiclesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVehiclesRequest) ProtoMessage() {}

func (x *ListVehiclesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVehiclesRequest.ProtoReflect.Descriptor instead.
func (*ListVehiclesRequest) Descriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{7}
}

func (x *ListVehiclesRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

type ListVehiclesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Vehicles      []*Vehicle             `protobuf:"bytes,1,rep,name=vehicles,proto3" json:"vehicles,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListVehiclesResponse) Reset() {
	*x = ListVehiclesResponse{}
	mi := &file_fleet_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListVehiclesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListVehiclesResponse) ProtoMessage() {}

func (x *ListVehiclesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListVehiclesResponse.ProtoReflect.Descriptor instead.
func (*ListVehiclesResponse) Descriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{8}
}

func (x *ListVehiclesResponse) GetVehicles() []*Vehicle {
	if x != nil {
		return x.Vehicles
	}
	return nil
}

type UpdateVehicleRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VehicleId     string                 `protobuf:"bytes,1,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	PlateNumber   string                 `protobuf:"bytes,2,opt,name=plate_number,json=plateNumber,proto3" json:"plate_number,omitempty"`
	VehicleType   string                 `protobuf:"bytes,3,opt,name=vehicle_type,json=vehicleType,proto3" json:"vehicle_type,omitempty"`
	Capacity      int32                  `protobuf:"varint,4,opt,name=capacity,proto3" json:"capacity,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateVehicleRequest) Reset() {
	*x = UpdateVehicleRequest{}
	mi := &file_fleet_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVehicleRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVehicleRequest) ProtoMessage() {}

func (x *UpdateVehicleRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVehicleRequest.ProtoReflect.Descriptor instead.
func (*UpdateVehicleRequest) Descriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{9}
}

func (x *UpdateVehicleRequest) GetVehicleId() string {
	if x != nil {
		return x.VehicleId
	}
	return ""
}

func (x *UpdateVehicleRequest) GetPlateNumber() string {
	if x != nil {
		return x.PlateNumber
	}
	return ""
}

func (x *UpdateVehicleRequest) GetVehicleType() string {
	if x != nil {
		return x.VehicleType
	}
	return ""
}

func (x *UpdateVehicleRequest) GetCapacity() int32 {
	if x != nil {
		return x.Capacity
	}
	return 0
}

type UpdateVehicleResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateVehicleResponse) Reset() {
	*x = UpdateVehicleResponse{}
	mi := &file_fleet_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVehicleResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVehicleResponse) ProtoMessage() {}

func (x *UpdateVehicleResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVehicleResponse.ProtoReflect.Descriptor instead.
func (*UpdateVehicleResponse) Descriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateVehicleResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UpdateVehicleStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	VehicleId     string                 `protobuf:"bytes,1,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // active / inactive
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateVehicleStatusRequest) Reset() {
	*x = UpdateVehicleStatusRequest{}
	mi := &file_fleet_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVehicleStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVehicleStatusRequest) ProtoMessage() {}

func (x *UpdateVehicleStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVehicleStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateVehicleStatusRequest) Descriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateVehicleStatusRequest) GetVehicleId() string {
	if x != nil {
		return x.VehicleId
	}
	return ""
}

func (x *UpdateVehicleStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateVehicleStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateVehicleStatusResponse) Reset() {
	*x = UpdateVehicleStatusResponse{}
	mi := &file_fleet_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVehicleStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVehicleStatusResponse) ProtoMessage() {}

func (x *UpdateVehicleStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVehicleStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateVehicleStatusResponse) Descriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateVehicleStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CreateDriverRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	FirstName      string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName       string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	VehicleId      string                 `protobuf:"bytes,4,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateDriverRequest) Reset() {
	*x = CreateDriverRequest{}
	mi := &file_fleet_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDriverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDriverRequest) ProtoMessage() {}

func (x *CreateDriverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDriverRequest.ProtoReflect.Descriptor instead.
func (*CreateDriverRequest) Descriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{13}
}

func (x *CreateDriverRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *CreateDriverRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *CreateDriverRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

func (x *CreateDriverRequest) GetVehicleId() string {
	if x != nil {
		return x.VehicleId
	}
	return ""
}

type CreateDriverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Driver        *Driver                `protobuf:"bytes,1,opt,name=driver,proto3" json:"driver,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDriverResponse) Reset() {
	*x = CreateDriverResponse{}
	mi := &file_fleet_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDriverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDriverResponse) ProtoMessage() {}

func (x *CreateDriverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDriverResponse.ProtoReflect.Descriptor instead.
func (*CreateDriverResponse) Descriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{14}
}

func (x *CreateDriverResponse) GetDriver() *Driver {
	if x != nil {
		return x.Driver
	}
	return nil
}

type ListDriversRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListDriversRequest) Reset() {
	*x = ListDriversRequest{}
	mi := &file_fleet_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDriversRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDriversRequest) ProtoMessage() {}

func (x *ListDriversRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDriversRequest.ProtoReflect.Descriptor instead.
func (*ListDriversRequest) Descriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{15}
}

func (x *ListDriversRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

type ListDriversResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Drivers       []*Driver              `protobuf:"bytes,1,rep,name=drivers,proto3" json:"drivers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDriversResponse) Reset() {
	*x = ListDriversResponse{}
	mi := &file_fleet_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDriversResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDriversResponse) ProtoMessage() {}

func (x *ListDriversResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDriversResponse.ProtoReflect.Descriptor instead.
func (*ListDriversResponse) Descriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{16}
}

func (x *ListDriversResponse) GetDrivers() []*Driver {
	if x != nil {
		return x.Drivers
	}
	return nil
}

type UpdateDriverRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	FirstName     string                 `protobuf:"bytes,2,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName      string                 `protobuf:"bytes,3,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDriverRequest) Reset() {
	*x = UpdateDriverRequest{}
	mi := &file_fleet_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDriverRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDriverRequest) ProtoMessage() {}

func (x *UpdateDriverRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDriverRequest.ProtoReflect.Descriptor instead.
func (*UpdateDriverRequest) Descriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{17}
}

func (x *UpdateDriverRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *UpdateDriverRequest) GetFirstName() string {
	if x != nil {
		return x.FirstName
	}
	return ""
}

func (x *UpdateDriverRequest) GetLastName() string {
	if x != nil {
		return x.LastName
	}
	return ""
}

type UpdateDriverResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDriverResponse) Reset() {
	*x = UpdateDriverResponse{}
	mi := &file_fleet_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDriverResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDriverResponse) ProtoMessage() {}

func (x *UpdateDriverResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDriverResponse.ProtoReflect.Descriptor instead.
func (*UpdateDriverResponse) Descriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{18}
}

func (x *UpdateDriverResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type UpdateDriverStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      string                 `protobuf:"bytes,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"` // active / inactive
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDriverStatusRequest) Reset() {
	*x = UpdateDriverStatusRequest{}
	mi := &file_fleet_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDriverStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDriverStatusRequest) ProtoMessage() {}

func (x *UpdateDriverStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDriverStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateDriverStatusRequest) Descriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{19}
}

func (x *UpdateDriverStatusRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

func (x *UpdateDriverStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type UpdateDriverStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDriverStatusResponse) Reset() {
	*x = UpdateDriverStatusResponse{}
	mi := &file_fleet_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDriverStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDriverStatusResponse) ProtoMessage() {}

func (x *UpdateDriverStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDriverStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateDriverStatusResponse) Descriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{20}
}

func (x *UpdateDriverStatusResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CreateTripRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	VehicleId      string                 `protobuf:"bytes,2,opt,name=vehicle_id,json=vehicleId,proto3" json:"vehicle_id,omitempty"`
	DriverId       string                 `protobuf:"bytes,3,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateTripRequest) Reset() {
	*x = CreateTripRequest{}
	mi := &file_fleet_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTripRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTripRequest) ProtoMessage() {}

func (x *CreateTripRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTripRequest.ProtoReflect.Descriptor instead.
func (*CreateTripRequest) Descriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{21}
}

func (x *CreateTripRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

func (x *CreateTripRequest) GetVehicleId() string {
	if x != nil {
		return x.VehicleId
	}
	return ""
}

func (x *CreateTripRequest) GetDriverId() string {
	if x != nil {
		return x.DriverId
	}
	return ""
}

type CreateTripResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trip          *Trip                  `protobuf:"bytes,1,opt,name=trip,proto3" json:"trip,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTripResponse) Reset() {
	*x = CreateTripResponse{}
	mi := &file_fleet_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTripResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTripResponse) ProtoMessage() {}

func (x *CreateTripResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTripResponse.ProtoReflect.Descriptor instead.
func (*CreateTripResponse) Descriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{22}
}

func (x *CreateTripResponse) GetTrip() *Trip {
	if x != nil {
		return x.Trip
	}
	return nil
}

type ListTripsRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrganizationId string                 `protobuf:"bytes,1,opt,name=organization_id,json=organizationId,proto3" json:"organization_id,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ListTripsRequest) Reset() {
	*x = ListTripsRequest{}
	mi := &file_fleet_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTripsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTripsRequest) ProtoMessage() {}

func (x *ListTripsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTripsRequest.ProtoReflect.Descriptor instead.
func (*ListTripsRequest) Descriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{23}
}

func (x *ListTripsRequest) GetOrganizationId() string {
	if x != nil {
		return x.OrganizationId
	}
	return ""
}

type ListTripsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Trips         []*Trip                `protobuf:"bytes,1,rep,name=trips,proto3" json:"trips,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListTripsResponse) Reset() {
	*x = ListTripsResponse{}
	mi := &file_fleet_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListTripsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListTripsResponse) ProtoMessage() {}

func (x *ListTripsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListTripsResponse.ProtoReflect.Descriptor instead.
func (*ListTripsResponse) Descriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{24}
}

func (x *ListTripsResponse) GetTrips() []*Trip {
	if x != nil {
		return x.Trips
	}
	return nil
}

type StartTripRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TripId        string                 `protobuf:"bytes,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartTripRequest) Reset() {
	*x = StartTripRequest{}
	mi := &file_fleet_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTripRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTripRequest) ProtoMessage() {}

func (x *StartTripRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTripRequest.ProtoReflect.Descriptor instead.
func (*StartTripRequest) Descriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{25}
}

func (x *StartTripRequest) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

type StartTripResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StartTripResponse) Reset() {
	*x = StartTripResponse{}
	mi := &file_fleet_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StartTripResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StartTripResponse) ProtoMessage() {}

func (x *StartTripResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StartTripResponse.ProtoReflect.Descriptor instead.
func (*StartTripResponse) Descriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{26}
}

func (x *StartTripResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type CompleteTripRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TripId        string                 `protobuf:"bytes,1,opt,name=trip_id,json=tripId,proto3" json:"trip_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteTripRequest) Reset() {
	*x = CompleteTripRequest{}
	mi := &file_fleet_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteTripRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteTripRequest) ProtoMessage() {}

func (x *CompleteTripRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteTripRequest.ProtoReflect.Descriptor instead.
func (*CompleteTripRequest) Descriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{27}
}

func (x *CompleteTripRequest) GetTripId() string {
	if x != nil {
		return x.TripId
	}
	return ""
}

type CompleteTripResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CompleteTripResponse) Reset() {
	*x = CompleteTripResponse{}
	mi := &file_fleet_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CompleteTripResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CompleteTripResponse) ProtoMessage() {}

func (x *CompleteTripResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CompleteTripResponse.ProtoReflect.Descriptor instead.
func (*CompleteTripResponse) Descriptor() ([]byte, []int) {
	return file_fleet_proto_rawDescGZIP(), []int{28}
}

func (x *CompleteTripResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

var File_fleet_proto protoreflect.FileDescriptor

const file_fleet_proto_rawDesc = "" +
	"\n" +
	"\vfleet.proto\x12\x05fleet\"\xea\x01\n" +
	"\aVehicle\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x01 \x01(\tR\tvehicleId\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12!\n" +
	"\fplate_number\x18\x03 \x01(\tR\vplateNumber\x12!\n" +
	"\fvehicle_type\x18\x04 \x01(\tR\vvehicleType\x12\x1a\n" +
	"\bcapacity\x18\x05 \x01(\x05R\bcapacity\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\"\xe0\x01\n" +
	"\x06Driver\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12\x1d\n" +
	"\n" +
	"first_name\x18\x03 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x04 \x01(\tR\blastName\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x05 \x01(\tR\tvehicleId\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"created_at\x18\a \x01(\x03R\tcreatedAt\"\xf5\x01\n" +
	"\x04Trip\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\tR\x06tripId\x12'\n" +
	"\x0forganization_id\x18\x02 \x01(\tR\x0eorganizationId\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x03 \x01(\tR\tvehicleId\x12\x1b\n" +
	"\tdriver_id\x18\x04 \x01(\tR\bdriverId\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x12\x1d\n" +
	"\n" +
	"start_time\x18\x06 \x01(\x03R\tstartTime\x12\x19\n" +
	"\bend_time\x18\a \x01(\x03R\aendTime\x12\x1d\n" +
	"\n" +
	"created_at\x18\b \x01(\x03R\tcreatedAt\"\xa1\x01\n" +
	"\x14CreateVehicleRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12!\n" +
	"\fplate_number\x18\x02 \x01(\tR\vplateNumber\x12!\n" +
	"\fvehicle_type\x18\x03 \x01(\tR\vvehicleType\x12\x1a\n" +
	"\bcapacity\x18\x04 \x01(\x05R\bcapacity\"A\n" +
	"\x15CreateVehicleResponse\x12(\n" +
	"\avehicle\x18\x01 \x01(\v2\x0e.fleet.VehicleR\avehicle\"2\n" +
	"\x11GetVehicleRequest\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x01 \x01(\tR\tvehicleId\">\n" +
	"\x12GetVehicleResponse\x12(\n" +
	"\avehicle\x18\x01 \x01(\v2\x0e.fleet.VehicleR\avehicle\">\n" +
	"\x13ListVehiclesRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\"B\n" +
	"\x14ListVehiclesResponse\x12*\n" +
	"\bvehicles\x18\x01 \x03(\v2\x0e.fleet.VehicleR\bvehicles\"\x97\x01\n" +
	"\x14UpdateVehicleRequest\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x01 \x01(\tR\tvehicleId\x12!\n" +
	"\fplate_number\x18\x02 \x01(\tR\vplateNumber\x12!\n" +
	"\fvehicle_type\x18\x03 \x01(\tR\vvehicleType\x12\x1a\n" +
	"\bcapacity\x18\x04 \x01(\x05R\bcapacity\"1\n" +
	"\x15UpdateVehicleResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"S\n" +
	"\x1aUpdateVehicleStatusRequest\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x01 \x01(\tR\tvehicleId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"7\n" +
	"\x1bUpdateVehicleStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\x99\x01\n" +
	"\x13CreateDriverRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x04 \x01(\tR\tvehicleId\"=\n" +
	"\x14CreateDriverResponse\x12%\n" +
	"\x06driver\x18\x01 \x01(\v2\r.fleet.DriverR\x06driver\"=\n" +
	"\x12ListDriversRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\">\n" +
	"\x13ListDriversResponse\x12'\n" +
	"\adrivers\x18\x01 \x03(\v2\r.fleet.DriverR\adrivers\"n\n" +
	"\x13UpdateDriverRequest\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12\x1d\n" +
	"\n" +
	"first_name\x18\x02 \x01(\tR\tfirstName\x12\x1b\n" +
	"\tlast_name\x18\x03 \x01(\tR\blastName\"0\n" +
	"\x14UpdateDriverResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"P\n" +
	"\x19UpdateDriverStatusRequest\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\tR\bdriverId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\"6\n" +
	"\x1aUpdateDriverStatusResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"x\n" +
	"\x11CreateTripRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\x12\x1d\n" +
	"\n" +
	"vehicle_id\x18\x02 \x01(\tR\tvehicleId\x12\x1b\n" +
	"\tdriver_id\x18\x03 \x01(\tR\bdriverId\"5\n" +
	"\x12CreateTripResponse\x12\x1f\n" +
	"\x04trip\x18\x01 \x01(\v2\v.fleet.TripR\x04trip\";\n" +
	"\x10ListTripsRequest\x12'\n" +
	"\x0forganization_id\x18\x01 \x01(\tR\x0eorganizationId\"6\n" +
	"\x11ListTripsResponse\x12!\n" +
	"\x05trips\x18\x01 \x03(\v2\v.fleet.TripR\x05trips\"+\n" +
	"\x10StartTripRequest\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\tR\x06tripId\"-\n" +
	"\x11StartTripResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\".\n" +
	"\x13CompleteTripRequest\x12\x17\n" +
	"\atrip_id\x18\x01 \x01(\tR\x06tripId\"0\n" +
	"\x14CompleteTripResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess2\xcf\a\n" +
	"\fFleetService\x12J\n" +
	"\rCreateVehicle\x12\x1b.fleet.CreateVehicleRequest\x1a\x1c.fleet.CreateVehicleResponse\x12A\n" +
	"\n" +
	"GetVehicle\x12\x18.fleet.GetVehicleRequest\x1a\x19.fleet.GetVehicleResponse\x12G\n" +
	"\fListVehicles\x12\x1a.fleet.ListVehiclesRequest\x1a\x1b.fleet.ListVehiclesResponse\x12J\n" +
	"\rUpdateVehicle\x12\x1b.fleet.UpdateVehicleRequest\x1a\x1c.fleet.UpdateVehicleResponse\x12\\\n" +
	"\x13UpdateVehicleStatus\x12!.fleet.UpdateVehicleStatusRequest\x1a\".fleet.UpdateVehicleStatusResponse\x12G\n" +
	"\fCreateDriver\x12\x1a.fleet.CreateDriverRequest\x1a\x1b.fleet.CreateDriverResponse\x12D\n" +
	"\vListDrivers\x12\x19.fleet.ListDriversRequest\x1a\x1a.fleet.ListDriversResponse\x12G\n" +
	"\fUpdateDriver\x12\x1a.fleet.UpdateDriverRequest\x1a\x1b.fleet.UpdateDriverResponse\x12Y\n" +
	"\x12UpdateDriverStatus\x12 .fleet.UpdateDriverStatusRequest\x1a!.fleet.UpdateDriverStatusResponse\x12A\n" +
	"\n" +
	"CreateTrip\x12\x18.fleet.CreateTripRequest\x1a\x19.fleet.CreateTripResponse\x12>\n" +
	"\tListTrips\x12\x17.fleet.ListTripsRequest\x1a\x18.fleet.ListTripsResponse\x12>\n" +
	"\tStartTrip\x12\x17.fleet.StartTripRequest\x1a\x18.fleet.StartTripResponse\x12G\n" +
	"\fCompleteTrip\x12\x1a.fleet.CompleteTripRequest\x1a\x1b.fleet.CompleteTripResponseB\x1aZ\x18shared/proto/fleet;fleetb\x06proto3"

var (
	file_fleet_proto_rawDescOnce sync.Once
	file_fleet_proto_rawDescData []byte
)

func file_fleet_proto_rawDescGZIP() []byte {
	file_fleet_proto_rawDescOnce.Do(func() {
		file_fleet_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fleet_proto_rawDesc), len(file_fleet_proto_rawDesc)))
	})
	return file_fleet_proto_rawDescData
}

var file_fleet_proto_msgTypes = make([]protoimpl.MessageInfo, 29)
var file_fleet_proto_goTypes = []any{
	(*Vehicle)(nil),                     // 0: fleet.Vehicle
	(*Driver)(nil),                      // 1: fleet.Driver
	(*Trip)(nil),                        // 2: fleet.Trip
	(*CreateVehicleRequest)(nil),        // 3: fleet.CreateVehicleRequest
	(*CreateVehicleResponse)(nil),       // 4: fleet.CreateVehicleResponse
	(*GetVehicleRequest)(nil),           // 5: fleet.GetVehicleRequest
	(*GetVehicleResponse)(nil),          // 6: fleet.GetVehicleResponse
	(*ListVehiclesRequest)(nil),         // 7: fleet.ListVehiclesRequest
	(*ListVehiclesResponse)(nil),        // 8: fleet.ListVehiclesResponse
	(*UpdateVehicleRequest)(nil),        // 9: fleet.UpdateVehicleRequest
	(*UpdateVehicleResponse)(nil),       // 10: fleet.UpdateVehicleResponse
	(*UpdateVehicleStatusRequest)(nil),  // 11: fleet.UpdateVehicleStatusRequest
	(*UpdateVehicleStatusResponse)(nil), // 12: fleet.UpdateVehicleStatusResponse
	(*CreateDriverRequest)(nil),         // 13: fleet.CreateDriverRequest
	(*CreateDriverResponse)(nil),        // 14: fleet.CreateDriverResponse
	(*ListDriversRequest)(nil),          // 15: fleet.ListDriversRequest
	(*ListDriversResponse)(nil),         // 16: fleet.ListDriversResponse
	(*UpdateDriverRequest)(nil),         // 17: fleet.UpdateDriverRequest
	(*UpdateDriverResponse)(nil),        // 18: fleet.UpdateDriverResponse
	(*UpdateDriverStatusRequest)(nil),   // 19: fleet.UpdateDriverStatusRequest
	(*UpdateDriverStatusResponse)(nil),  // 20: fleet.UpdateDriverStatusResponse
	(*CreateTripRequest)(nil),           // 21: fleet.CreateTripRequest
	(*CreateTripResponse)(nil),          // 22: fleet.CreateTripResponse
	(*ListTripsRequest)(nil),            // 23: fleet.ListTripsRequest
	(*ListTripsResponse)(nil),           // 24: fleet.ListTripsResponse
	(*StartTripRequest)(nil),            // 25: fleet.StartTripRequest
	(*StartTripResponse)(nil),           // 26: fleet.StartTripResponse
	(*CompleteTripRequest)(nil),         // 27: fleet.CompleteTripRequest
	(*CompleteTripResponse)(nil),        // 28: fleet.CompleteTripResponse
}
var file_fleet_proto_depIdxs = []int32{
	0,  // 0: fleet.CreateVehicleResponse.vehicle:type_name -> fleet.Vehicle
	0,  // 1: fleet.GetVehicleResponse.vehicle:type_name -> fleet.Vehicle
	0,  // 2: fleet.ListVehiclesResponse.vehicles:type_name -> fleet.Vehicle
	1,  // 3: fleet.CreateDriverResponse.driver:type_name -> fleet.Driver
	1,  // 4: fleet.ListDriversResponse.drivers:type_name -> fleet.Driver
	2,  // 5: fleet.CreateTripResponse.trip:type_name -> fleet.Trip
	2,  // 6: fleet.ListTripsResponse.trips:type_name -> fleet.Trip
	3,  // 7: fleet.FleetService.CreateVehicle:input_type -> fleet.CreateVehicleRequest
	5,  // 8: fleet.FleetService.GetVehicle:input_type -> fleet.GetVehicleRequest
	7,  // 9: fleet.FleetService.ListVehicles:input_type -> fleet.ListVehiclesRequest
	9,  // 10: fleet.FleetService.UpdateVehicle:input_type -> fleet.UpdateVehicleRequest
	11, // 11: fleet.FleetService.UpdateVehicleStatus:input_type -> fleet.UpdateVehicleStatusRequest
	13, // 12: fleet.FleetService.CreateDriver:input_type -> fleet.CreateDriverRequest
	15, // 13: fleet.FleetService.ListDrivers:input_type -> fleet.ListDriversRequest
	17, // 14: fleet.FleetService.UpdateDriver:input_type -> fleet.UpdateDriverRequest
	19, // 15: fleet.FleetService.UpdateDriverStatus:input_type -> fleet.UpdateDriverStatusRequest
	21, // 16: fleet.FleetService.CreateTrip:input_type -> fleet.CreateTripRequest
	23, // 17: fleet.FleetService.ListTrips:input_type -> fleet.ListTripsRequest
	25, // 18: fleet.FleetService.StartTrip:input_type -> fleet.StartTripRequest
	27, // 19: fleet.FleetService.CompleteTrip:input_type -> fleet.CompleteTripRequest
	4,  // 20: fleet.FleetService.CreateVehicle:output_type -> fleet.CreateVehicleResponse
	6,  // 21: fleet.FleetService.GetVehicle:output_type -> fleet.GetVehicleResponse
	8,  // 22: fleet.FleetService.ListVehicles:output_type -> fleet.ListVehiclesResponse
	10, // 23: fleet.FleetService.UpdateVehicle:output_type -> fleet.UpdateVehicleResponse
	12, // 24: fleet.FleetService.UpdateVehicleStatus:output_type -> fleet.UpdateVehicleStatusResponse
	14, // 25: fleet.FleetService.CreateDriver:output_type -> fleet.CreateDriverResponse
	16, // 26: fleet.FleetService.ListDrivers:output_type -> fleet.ListDriversResponse
	18, // 27: fleet.FleetService.UpdateDriver:output_type -> fleet.UpdateDriverResponse
	20, // 28: fleet.FleetService.UpdateDriverStatus:output_type -> fleet.UpdateDriverStatusResponse
	22, // 29: fleet.FleetService.CreateTrip:output_type -> fleet.CreateTripResponse
	24, // 30: fleet.FleetService.ListTrips:output_type -> fleet.ListTripsResponse
	26, // 31: fleet.FleetService.StartTrip:output_type -> fleet.StartTripResponse
	28, // 32: fleet.FleetService.CompleteTrip:output_type -> fleet.CompleteTripResponse
	20, // [20:33] is the sub-list for method output_type
	7,  // [7:20] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_fleet_proto_init() }
func file_fleet_proto_init() {
	if File_fleet_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fleet_proto_rawDesc), len(file_fleet_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   29,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_fleet_proto_goTypes,
		DependencyIndexes: file_fleet_proto_depIdxs,
		MessageInfos:      file_fleet_proto_msgTypes,
	}.Build()
	File_fleet_proto = out.File
	file_fleet_proto_goTypes = nil
	file_fleet_proto_depIdxs = nil
}
